COMCIFS/Powder_Dictionary

cif_pow.dic
This PR corrects the object id of the `_pd_proc.2theta_range_inc` by changing it from `2theta_range_min` to `2theta_range_inc`. Note, that this was necessary to avoid dREL name duplication (data items `_pd_proc.2theta_range_min` and `_pd_proc.2theta_range_inc` had the same dREL name `pd_proc_overall`.`2theta_range_min`).
=> Correct the object id of the _pd_proc.2theta_range_inc data item

cif_pow.dic
As per #4 fixing the treatment of `_pd_refln.wavelength_id` so that merging of `cif_core` into `cif_pow` treats `_pd_refln.wavelength_id` as if it were `_refln.wavelength_id` for the purposes of dREL methods, effectively adding `_pd_refln.wavelength_id` as an alias to `_refln.wavelength_id`. Also indicated in the definition that `_refln.wavelength_id` should be used.
=> Deprecated _pd_refln.wavelength_id.

cif_pow.dic
In the description of a few data names were references to other data names that used the CIF1.1 names. I've converted them to use CIF2.0.
=> fixed typos in data name references

cif_pow.dic
The attenuation coefficients currently given in the powder dictionary are linear absorption coefficients (LACs). The observed linear attenuation coefficient is also erroneously referred to as synonymous with mass attenuation coefficient (MAC).
There is no mention of MACs, either experimental or calculated.
This PR adds both experimental and calculated MACs.
This PR is incomplete, as it should also include a tag for describing how the MAC was calculated.
Sorry if this is the wrong way to do this, I was thinking on other things, and saw this was missing.
=> added obs and meas mass absorption coefficients

.github/workflows/main.yml, cif_pow.dic
This pull request fixes #18 and adds automatic checking of layout when any pull request is made. It rearranges the entire dictionary and adjusts whitespace, but does not change any semantics. I have used the `compare.jl` tool in my `julia_cif_tools` repository to check that yes, indeed, no semantics are changed.
=> Fixed layout of dictionary

cif_pow.dic
These fixes improve conformance with DDLm requirements:
1. Add `_units.code` values for all numeric items
2. Catch a few DDLm mistakes
Some errors are still flagged in the automated check, most likely to be a problem with the checking code.
Closes #25
=> Fix DDLm checking errors

cif_pow.dic
The (relevant part of the) current definition is
>100 times the ratio of the amount of standard added to the original sample mass.
which reads, to me, as: std wt% = 100 * mass(std) / mass(original sample) -> 100 * 1 / 3 = 33.3 wt% internal std 
which I believe is wrong, as you've added 1 g std to 3 g of original sample, giving 4 g. The mixed sample now contains 25% std.
The new definition is
> 100 times the mass of standard added divided by the sum of the mass of standard added and the original sample mass.
which reads, to me, as: std wt% = 100 * mass(std) / (mass(std) + mass(original sample)) -> 100 * 1 / (1+3) = 25 wt% internal std
=> clarify definition of _pd_calib.std_internal_mass_percent

cif_pow.dic
This is to ensure that weights are looped in the appropriate place. `pd_proc` is the right loop as we could notionally have different sets of weights and thereby produce different results, so `pd_meas` is not right.
Note that I've moved the period to before the `ls`. I think we can do this as the dotted form of the data names are not in common use yet. Closes (again) #33.
=> Assign _pd_proc_ls.weight to pd_proc

cif_pow.dic
The angstrom unit should not be capitalised.
=> Correct a typo in the PD_CALIB_D_TO_TOF category description.

cif_pow.dic
Fixes #34
This does use the "save_pd_instr." vs "_name.category_id  pd_meas" trick.
I don't know if you want to keep doing that.
=> add the ability to record detector circle radius

cif_pow.dic
Was initially looking just to address #42 .
But I now have other questions:
- `pd_meas.counts/intensity_` should be `Recorded`, not `Derived` - Addressed in this initial commit.
- Some ambiguity in definitions of `_pd_proc.intensity_norm` and `_pd_proc.intensity_net`: which one contains a bkg? From the definition of `_pd_calc.intensity_net`, I'm guessing `_pd_proc.intensity_net` is background-corrected and normalisation-corrected, and the other is just normalisation-corrected.
- Should all `_pd_proc.intensity_*` and `_pd_calc.intensity_*` have their values limited to be > 0 (as is currently)? ( c.f. discussion in [cif_core](https://github.com/COMCIFS/cif_core/pull/315#issuecomment-1328622630))
- The definitions of `_pd_meas.counts/intensity_background/container/monitor` say (amongst other …
=> updating of calc/meas/proc/.count/intensity definitions

#Untitled-4#, cif_pow.dic
A first pass at adding the capability to record quantiative phases analysis by internal or external standard approaches.
See #12
=> recording internal/external standard QPA

cif_pow.dic
from #60 
The only things that are still integers are:
- `_pd_meas.counts_background`, `counts_container`, `counts_monitor`, and `counts_total`.
- `_pd_meas.number_of_points`
- `_pd_pref_orient_March_Dollase.hkl`, `index_h`, `index_k`, `index_l`
- `_pd_pref_orient_sphericalharmonics.y_i`, `y_ij`, `y_j`
- `_pd_proc.number_of_points`
=> changed _pd_meas.time_of_flight and _pd_meas.step_count_time from Integer to Real

cif_pow.dic
Closes #21 . The current PR adds the category and child data names of `_pd_diffractogram.id`. This has the effect of linking the tabulated diffraction scan data to the concept of a diffractogram. When loops containing per-diffractogram, per-something-else information (e.g. per diffractogram per phase) are created, adding child data names of `_pd_diffractogram.id` formally states that the information in those loops depends on a particular diffractogram.
This is intended to be complementary to the block pointers used in pdCIF, and will work in situations where software is dictionary-aware but not pdCIF-aware.
=> Add pd_diffractogram category.

cif_pow.dic
I don't know if the `_dictionary_audit.revision` entry is required, as they are completely new categories...
=> add phase_id and diffractogram_id to PD_PREF_ORIENT_SPHERICAL_HARMONICS and  _MARCH_DOLLASE

cif_pow.dic
due to #46
These are (currently) the only two data items that can be deprecated due to the addition of `PD_QPA_INT_STD`.
=> Deprecate `_pd_calib.std_internal_mass_percent` and `*_su`

cif_pow.dic
I've added diffractogram_id and phase_id to the categories that allow the addition of per-phase intensities.
~~I've initially done something naughty, and put them in `PD_CALC_OVERALL` (this is a `Set` category),  but named them `_pd_calc_component.diffractogram/phase_id` (`_PD_CALC_COMPONENET` is a `Loop` category). I've chosen to do this as the new data items should be single-valued, and it allows for all `_pd_calc_component.*` data names to be used in a data block, as:~~ Ignore - I was talking bollocks.
`_PD_CALC_COMPONENT` now has `_pd_calc_component.diffractogram_id`,  `_pd_calc_component.phase_id`, as well as  `_pd_calc_component.point_id` to identify values.
```
data_component1
_pd_calc_component.phase_id		the_first_phase
_pd_calc_component.diffractogram_id	the_diff_patt
loop_ …
```
=> adding diffractogram_id and phase_id to per-phase intensities

cif_pow.dic
will close #67 
All of the current data items that hold block ID values used to point to the block containing that block id are now
```
_name.linked_item_id          '_pd_block.id'
_type.purpose                 Link
_type.source                  Assigned
_type.container               Single
_type.contents                Text
```
=> made block_id-related data items into formal links to `_pd_block.id`

cif_pow.dic
Some definitions of data items recording phase names were of type `Encode` and `Code`; this doesn't represent what they do/are, which is `Describe` and `Text`\*.
Also altered source for phase names of standards to be `Recorded`, otherwise `Assigned`.
\* This is one case where it would be nice to have a `_type.contents` value defined as "case-insensitive sequence of CIF2 characters"
=> Update definitions of phase names

cif_pow.dic
Update naming convention in line with other data items - the value is measure, not observed.
=> Renamed _pd_char.mass_atten_coef_mu_obs to  _pd_char.mass_atten_coef_mu_meas

cif_pow.dic
According to the CIF markup [1], the sequence for the infinity symbol is written with two backslashes (`\\infty`). Alternatively, infty/inf string could be used instead of sequence, but then the single backslash should be removed.
[1] https://journals.iucr.org/e/services/editguide.html
=> Add proper markup for the infinity symbol.

cif_pow.dic
Added some examples and removed reference to "crystal" - now amorphous phases can have names!
=> Update description of `_pd_phase.name` and add examples

cif_pow.dic
The backslashes were probably added in an attempt to properly fold the CIF text field, however, since this approach is not applied consistently, it would be better to remove these characters.
=> Remove excessive trailing backslash characters.

cif_pow.dic
will close #95 
Is this part OK?
> the incident radiation can be considered to be monochromatic
I'm thinking about a case like having a tube source and a Johannson mono, where the emission profile is some funky thing that still requires multiple wavelengths to model properly, but is "monochromatic". or even a curved graphite mono where there is still some residual kB radiation; i'd still call that "monochromatic", but it has been refined.
=> update description of _pd_proc.wavelength

cif_pow.dic
I started writing up how to report QPA, and realised I had overthought things.
Key changes:
- Removed `PD_QPA_RIR`.
-  I think this category was too narrowly focussed, and only served to specify that you did QPA by RIR. This was the only sort of QPA that was given it's own category
- Created `PD_QPA_CALIB_FACTOR` (`Set`, keyed on `_pd_qpa_calib_factor.phase_id`)
- This category takes over from `PD_QPA_RIR` inasmuch as it allows a phase to be given a `_pd_qpa_calib_factor.value`. For RIR, this data value is the RIR.
- In general, this category allows a phase to be given a calibration constant that allows the calculated intensities or scale factor of that phase (for any diffractogram) to be converted into a mass percentage via the appropriate algorithm, whatever that may be.
- Created …
=> update the QPA categories

cif_pow.dic
One of the dREL object IDs is probably incorrectly assigned.
=> Fix a duplicate dREL identifier

cif_pow.dic
This PR replaces several dotless data names from the `CIF_CORE` dictionary with their newer variants. Note that some of the referenced data items had been completely deprecated in the `CIF_CORE` dictionary and were therefore substituted by their replacement items (e.g. `_diffrn_radiation_type` was changed to `_diffrn_radiation_wavelength.type `). On the first glace the semantics seem to remain mostly the same, but it would be great if someone could double check.
=> Replace old data names with their newer variants in data item descriptions

cif_pow.dic
This category holds information on the diffractograms and phases used to calibrate the incident wavelength.
=> Created PD_CALIB_WAVELENGTH

cif_pow.dic
as mentioned in #79
Adding phase_id and/or diffractogram_id to categories as keys to allow multiple appearances of the various categories in difference blocks in the same data collection.
=> adding phase_id and/or diffractogram_id to categories as keys

cif_pow.dic
This category holds information on the corrections in X-coordinate used to calibrate detector_ids. It is trying to be a single category that can cover all of the different types of measured x-coordinate; 2Th, TOF, position, wavelength, detector_id (aka channel).
=> Created PD_CALIB_XCOORD

cif_pow.dic
I've added extra information on the influence of an internal standard on how weight fractions can be calculated.
In essence, any relative weight fraction can be converted to an absolute weight fraction (in the same manner) if an internal standard is present.
=> Enhance enumeration descriptions of `_pd_qpa_overall.method`

cif_pow.dic
Date taken from https://github.com/COMCIFS/Powder_Dictionary/commit/ecb7d10bc27acc1a8d8a66cdb7da6c216470d0f0
PD_SPEC was already changed. The revision sentence at the end was already correct.
=> Fixed update dates of PD_CHAR and PD_PREP

cif_pow.dic
Will close #113.
The `*.phase_id` and `*.diffractogram_id` tags were straight up deleted, as they were only added during this round of additions, and not previously released.
=> deprecate PD_*_AUTHOR

cif_pow.dic
Originally talked about in #53 and implemented in #89, #91, #92, and #93
The new categories 
- `PD_CALIB_DETECTED_INTENSITY`
- `PD_CALIB_INCIDENT_INTENSITY`
- `PD_CALIB_WAVELENGTH`
- `PD_CALIB_XCOORD`
- `PD_QPA_INTERNAL_STD` 
take up the functionality previously facilitated by
- `PD_CALIB `
- `PD_CALIB_OFFSET`
- `PD_CALIB_STD`
This PR is to deprecate redundant data items and categories.
.
I'm not deprecating `PD_CALIBRATION` yet, as I need to convince myself how I can calibrate a (for instance) energy-sensitive detector based on detector_id to energy (or position, or 2th or whatever...)
=> Deprecate calibration categories

cif_pow.dic
When we made `PD_PHASE` a `Set` caetgory, and `PD_BLOCK` a `Loop` category, we moved things around and we also added `_pd_phase.id` and `_pd_diffractogram.id` as the principle methods of identifying phases and patterns.
As in the old way, we could loop block IDs, we wanted to keep that same possibility, so we added `_pd_block_diffractogram.diffractogram_id` and `_pd_phase_block.phase_id` to keep that ability, however that requirement has been subsumed by individual `phase` and `diffractogram_id` tags in different categories.
Also, it conflates the block id methodology with the `phase` and `diffractogram.id` methodology of identifying things.
Straight up deletion, as they're new and not in any other previously released dictionary.
See also …
=> remove `_pd_block_diffractogram.diffractogram_id` and `_pd_phase_block.phase_id`

cif_pow.dic
=> Make `_pd_instr_detector.id` the primary source of detector id values

cif_pow.dic
As suggested in https://github.com/COMCIFS/Powder_Dictionary/pull/92#issuecomment-1493593082 and https://github.com/COMCIFS/Powder_Dictionary/issues/56#issuecomment-1584610839
`PD_CALIB_INCIDENT_INTENSITY` is best represented through the key `_pd_calib_incident_intensity.instr_id`. The calibration of incident intensity belongs to the incident source/optics, which are held in `PD_INSTR`. This is also a `Set` category, so we also need to change `PD_CALIB_INCIDENT_INTENSITY` to `Set`.
=> Category key and class for `PD_CALIB_INCIDENT_INTENSITY`

cif_pow.dic
From #129 
Peaks belong to a diffractogram, so need a diffractogram_id.
=> category keys for `PD_PEAK(_OVERALL)` 

cif_pow.dic
Change YYYY-DD-MM to YYYY-MM-DD
=> Incorrect datetime example in `_pd_block.id`

cif_pow.dic
will close #146 
Unrecognised due to categories and datanames changing after the descriptions were written.
=> Human-readable definitions no longer contain several unrecognised data names

cif_pow.dic
will close #148
except `_pd_pref_orient_march_dollase.hkl`.
=> Convert all `Array` and `Matrix`-type data items to be `List`

cif_pow.dic
Will close #152
Mentions of _pd_qpa_calib_factor.value leftover from previous definitions of dataitems.
=> replace mentions of _pd_qpa_calib_factor.value

cif_pow.dic
Incident intensity should be in counts per second, or per second, to allow for easy incorporation into normalisation routines.
These units don't exist yet, but I've changed it here and proposed them elsewhere https://github.com/COMCIFS/cif_core/pull/423
=> `_pd_calib_incident_intensity.incident_*` units change

cif_pow.dic
This PR addresses the issue discussed in PR #159.
Semantically, nothing should really change except it will be easier for software to properly handle the parent-child relationship of looped categories.
=> Change the linked item of several items to _pd_data.diffractogram_id.

cif_pow.dic
Remove "_list" from the data name, as it is already a `List`, so no need to do it twice.
=> Rename _pd_calc.component_intensity_*_list to _pd_calc.component_intensities_*

cif_pow.dic
As discussed in issue [1], all SU items should have their `_type.source` attribute set to 'Related'.
[1] https://github.com/COMCIFS/cif_core/issues/434
=> Change the _type.source attribute of all SU data items to 'Related'.

cif_pow.dic
A restart of #120 
There have been a bunch of changes in parallel to the block ID deprecation and changes have been lost through the various merging against master, so I started again.
Anyhoo...
The idea is that now we have `_pd_phase.id` and `_pd_diffractogram.id`, the vast majority of use cases for the block codes go away. Additionally, the new id values are machine readable. Furthermore, with the potential addition of `_audit_dataset.id`, the last vestiges of `_pd_block.id` are not needed.
What say you?
PS I still think that this change should alter the version number to 3.0.0
=> Deprecate pd block id again

cif_pow.dic
From https://github.com/COMCIFS/cif_core/issues/344#issuecomment-1763640090
Can now link a diffractogram and phases to the conditions under which the data were collected.
=> add diffrn_id to _pd_diffractogram and _pd_phase

cif_pow.dic
The repository check already validate it against the latest revision of the DDLm reference dictionary. This change makes it formal.
=> Set DDL conformance to version 4.2.0

cif_pow.dic
In the embedded revision description for version 2.4.1 it is stated that the `_pd_refln.wavelength_id` was deprecated after consultation with PDDMG. I assume that the same applies to `_pd_refln_wavelength_id`. These items are already declared as deprecated in the human-readable description of `_refln.wavelength_id`, the suggested change expresses it in a machine-readable way.
=> Explicitly deprecate several _refln.wavelength_id aliases

cif_pow.dic
These changes partially address issue #176.
The `_refln.f_complex` and `_refln.f_squared_meas` data items do not have default values in the coreCIF dictionary therefore they should not have default values in the pdCIF dictionary. Alternatively, default values could be added to the definitions in coreCIF.
Some dREL code was refolded for readability, but was left unchanged otherwise.
=> Homogenise redefined coreCIF items

cif_pow.dic
This is unnecessary as peak extraction procedure can be described independent of a particular diffractogram. Fixes #192.
=> Drop _pd_peak_overall.diffractogram_id

cif_pow.dic
Data names whose values were a function of the other key data name have been removed as keys (but retained as data names).
Fixes #194 .
=> Remove incorrect key data names from PD_SPEC and PD_PREP

cif_pow.dic
Will close #159 
Added clarification that identical values of `_pd_calc.point_id`, `_pd_calc_component.point_id`, `_pd_proc.point_id`, `_pd_meas.point_id`, and `_pd_data.point_id` point to the same data point. That is, you cannot independently assign values to the various category keys.
=> Update linked _pd_data.point_id descriptions

cif_pow.dic
=> Add example - PD_CALC_OVERALL

cif_pow.dic
=> example PD_PHASE_MASS

cif_pow.dic
Another thing I missed in the previous merge. The parentheses were unbalanced, it would be great if @rowlesmr could confirm this is what they meant.
=> Fix formula in the PD_PROC_LS example

cif_pow.dic
=> example PD_QPA_CALIB_FACTOR

cif_pow.dic
from #124
Should there be a _pd_peak.overall_id to link the peaks to their overall methods?
=> examples PD_PEAK

cif_pow.dic
from #72 
Added `_pd_calc.intensity_bkg` to maintain consistency with the naming scheme within PD_CALC. To be used instead of `_pd_proc.intensity_bkg_calc`, which was the only other way of recording a point-wise calculated bkg.
Also, is defined as a `Number`, so no need for an SU.
I didn't deprecate `_pd_proc.intensity_bkg_calc`, as although it is essentially a drop-in replacement, it is a `Number`, vs `Measurand`.
=> add _pd_calc.intensity_bkg

cif_pow.dic
from my writing volG things
Added `_pd_meas_overall.step_count_time` to give a step count time on a per-diffractogram basis, and updated description of `_pd_meas.step_count_time` to say that you should prefer `_pd_meas_overall.step_count_time` if the step time is constant for each point.
There are a couple of examples in the powder chapter where `_pd_meas.step_count_time` (a loop category data name) is used in a Set-like manner to describe the count time of a diffractogram (containing looped `_pd_meas.* names) which is given in the same data block.
Don't think that is entirely kosher.
`_pd_meas_overall.step_count_time` solves this.
=> added _pd_meas_overall.step_count_time

cif_pow.dic
=> example PD_QPA_INTERNAL_STD

cif_pow.dic
from #124
Instrument examples are split between PD_INSTR and PD_INSTR_DETECTOR.
I think the category descriptions need to be updated to point our that the former is source to specimen, and the latter is specimen to detector(s).
=> examples PD_INSTR

cif_pow.dic
This is a category for the overall intensity calibration of a detector. 1 value per detector, so makes no sense to be also keyed on an opaque ID.
=> rekey PD_CALIB_DETECTED_INTENSITY and add examples

cif_pow.dic
=> examples PD_QPA_EXTERNAL_STD

.github/workflows/main.yml, cif_pow.dic
from https://github.com/COMCIFS/MultiBlock_Dictionary/pull/31#issuecomment-3018233983
>`_pd_diffractogram` will want to point to `_diffrn_scan.scan_id` and `_diffrn_scan_frame.frame_id` if it is derived from a 2D measurement and there is more than one scan + frame.
Starting the process to allow a diffractogram to link to the specifc imgCIF frame and/or scan from which it was originally measured
=> _pd_diffractogram links to imgCIF

cif_pow.dic
from #124 
should PD_INSTR_DETECTOR have _pd_instr_detector.instr_id to link the detectors to the instrument?
=> examples PD_INSTR_DETECTOR
