cif_pow.dic
Here you go. A first pass at updating the tags that use datetimes.
=> added more examples and clarified datetime tags

cif_pow.dic
first pass of adding d to TOF calibration data names 
This is for #10
=> add PD_CALIB_D_TO_TOF

cif_pow.dic
PD_BLOCK is now a loop.
Closes #43
=> PD_BLOCK is now a loop

cif_pow.dic
I was quite liberal with what I changed; if I though it could possibly have an SU, it got changed.
I didn't add *.2theta_range_inc|max|min, as errors in those values would be probably be cumulative over the entire range.
from #37
=> updated many names from Number -> Measurand

cif_pow.dic
Initial go at adding per phase calculated intensities.
I put in PD_CALC_COMPONENT as a child of PD_DATA, so they can be looped with all the other data.
=> Per phase calculated intensities

cif_pow.dic
This is very much an alpha version.
=> Add new preferred orientation data names

cif_pow.dic
Reverts COMCIFS/Powder_Dictionary#51
Accidental deletion of new preferred orientation data names.
=> Revert "Revert "Add new preferred orientation data names""

#Untitled-4#
I somehow managed to commit a temporary file...
=> Delete errrant file: #Untitled-4#

cif_pow.dic
=> alter *sphericalharmonics* to *spherical_harmonics*

cif_pow.dic
Create PD_AMORPHOUS
as mentioned https://github.com/COMCIFS/Powder_Dictionary/issues/23#issuecomment-1288261647
=> created PD_AMORPHOUS. altered definition of PD_PHASE

cif_pow.dic
There is a clash with a date from a dictionary that is being imported.
=> update dictionary date

cif_pow.dic
Will close #82
Update description of _pd_proc.info_datetime to maintain consistency with its Set category.
=> Update description of _pd_proc.info_datetime 

cif_pow.dic
This PR fixes several incorrect data names and updates the way references to sets of data items are provided.
=> Fix data names in descriptions.

cif_pow.dic
=> added enumeration range for `_pd_qpa_int_std.mass_percent`

cif_pow.dic
will close #99 
removed reference to 'file' in description of _pd_calibration.conversion_eqn
=> removed reference to 'file' in description of _pd_calibration.conversion_eqn

cif_pow.dic
Addresses #84 
An initial attempt. I need to get my copy of "A Practical Guide for the Preparation of Specimens for X-Ray Fluorescence and X-Ray Diffraction Analysis" from work to make a better explanation.
=> initial attempt at differentiating material, sample, and specimen.

cif_pow.dic
=> update alias for `_pd_phase_mass.percent`

cif_pow.dic, cif_pow.dic~
Starting to add some examples.
Let's start with `PD_CALC_COMPONENT`.
=> Adding example data item usage

cif_pow.dic
add category key _pd_proc_ls.diffractogram_id
=> add category key _pd_proc_ls.diffractogram_id

cif_pow.dic
from https://github.com/COMCIFS/cif_core/pull/381#issuecomment-1543249332: saveframe names to be lowercase.
=> make all save frame names lower-case

cif_pow.dic
Sorry for separate PR's, the detection of such discrepancies is not fully automated or tested yet.
=> Fix more data names.

cif_pow.dic
=> Clarify description of `_pd_meas.rocking_angle`

cif_pow.dic
and fixed formatting of some equations
Just an experiment to see if it works.
=> replace markup with unicode characters

cif_pow.dic
This PR should be merged only **after** merging PR https://github.com/COMCIFS/cif_core/pull/492!
=> Update CIF_CORE import statement

cif_pow.dic
Fixed some typos in the PO categories while writing up for volG
=> fix PO typos

cif_pow.dic
=> example PD_SPEC

cif_pow.dic
I missed the typo in the last review of the branch.
=> Fix typo in the last name "Hastings"

cif_pow.dic
=> example _pd_phase.id

cif_pow.dic
From #110 
Added data items to record crystallographic density, linear absorption coeff, and mass absorption coeff of a phase.
=> add _pd_phase.* data items

cif_pow.dic
=> fix some incorrect human-readable data names
